services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mcb
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    command: sh -c 'npm install && npm run dev'
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
volumes:
  db_data:
