import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#4A90E2',
    primaryContainer: '#E3F2FD',
    secondary: '#50C878',
    secondaryContainer: '#E8F5E8',
    tertiary: '#FF6B6B',
    tertiaryContainer: '#FFE8E8',
    surface: '#FFFFFF',
    surfaceVariant: '#F5F5F5',
    background: '#FAFAFA',
    error: '#FF5252',
    errorContainer: '#FFEBEE',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onTertiary: '#FFFFFF',
    onSurface: '#1A1A1A',
    onSurfaceVariant: '#666666',
    onBackground: '#1A1A1A',
    onError: '#FFFFFF',
    outline: '#E0E0E0',
    outlineVariant: '#F0F0F0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2A2A2A',
    inverseOnSurface: '#FFFFFF',
    inversePrimary: '#4A90E2',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#FFFFFF',
      level3: '#FFFFFF',
      level4: '#FFFFFF',
      level5: '#FFFFFF',
    },
  },
  roundness: 12,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#6BB6FF',
    primaryContainer: '#1A365D',
    secondary: '#7ED321',
    secondaryContainer: '#2D5016',
    tertiary: '#FF8A80',
    tertiaryContainer: '#5D1F1A',
    surface: '#1A1A1A',
    surfaceVariant: '#2A2A2A',
    background: '#121212',
    error: '#FF6B6B',
    errorContainer: '#5D1F1A',
    onPrimary: '#000000',
    onSecondary: '#000000',
    onTertiary: '#000000',
    onSurface: '#FFFFFF',
    onSurfaceVariant: '#CCCCCC',
    onBackground: '#FFFFFF',
    onError: '#000000',
    outline: '#404040',
    outlineVariant: '#2A2A2A',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#E0E0E0',
    inverseOnSurface: '#1A1A1A',
    inversePrimary: '#4A90E2',
    elevation: {
      level0: 'transparent',
      level1: '#1F1F1F',
      level2: '#232323',
      level3: '#252525',
      level4: '#272727',
      level5: '#2A2A2A',
    },
  },
  roundness: 12,
};

export type Theme = typeof lightTheme;
